apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-problem-12
spec:
  selector:
    matchLabels:
      app: k8s-problem-12
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-problem-12
    spec:
      containers:
        - name: hello-app
          image: hashicorp/http-echo
          args:
            - "-text=hello"