apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-problem-11
spec:
  selector:
    matchLabels:
      app: k8s-problem-11
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-problem-11
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - "sleep 3600"
          name: k8s-problem-11
          image: k8s.gcr.io/busybox
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
