apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-problem-13
spec:
  selector:
    matchLabels:
      app: k8s-problem-13
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-problem-13
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostnames
                    operator: Exists
      containers:
        - command: ["sleep", "3600"]
          name: k8s-problem-13
          image: k8s.gcr.io/busybox
