apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-problem-10
spec:
  selector:
    matchLabels:
      app: k8s-problem-10
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-problem-10
    spec:
      containers:
        - name: echo-app
          image: hashicorp/http-echo
          args:
            - "-text=hello"
          resources:
            requests:
              memory: "10Gi"
              cpu: "50m"
            limits:
              memory: "10Gi"
              cpu: "50m"